services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest 
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 5s
      retries: 10
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 10

  ffnvr:
    build:
      context: ../.
      dockerfile: ./ci-cd/Dockerfile
    env_file:
      - ../.env
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
